package view;

import java.awt.Point;
import java.util.Observable;

import model.IElement;
import model.ILevel;

public class LevelMock implements ILevel {

	@Override
	public int getWidth() {
		// TODO Autogenerated method stub
		return 0;
	}

	@Override
	public int getHeight() {
		// TODO Autogenerated method stub
		return 0;
	}

	@Override
	public IElement getOnTheLevelXY(int x, int y) {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public void setOnTheLevelXY(int x, int y, IElement element) {
		// TODO Autogenerated method stub

	}

	@Override
	public Observable getObservable() {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public void setElementHasChanged() {
		// TODO Autogenerated method stub

	}

	@Override
	public Point getPlayerBluePosition() {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public Point getPlayerRedPosition() {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public void RecordPartie(String Winner, String Loser, int Time) {
		// TODO Auto-generated method stub
		
	}

}