package view;

import java.awt.Image;
import java.awt.Point;

import model.IMobile;
import model.Permeability;
import model.Sprite;

public class PlayerRedMock implements IMobile {

	@Override
	public Sprite getSprite() {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public Permeability getPermeability() {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public Image getImage() {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public void moveUp() {
		// TODO Autogenerated method stub

	}

	@Override
	public void moveLeft() {
		// TODO Autogenerated method stub

	}

	@Override
	public void moveDown() {
		// TODO Autogenerated method stub

	}

	@Override
	public void moveRight() {
		// TODO Autogenerated method stub

	}

	@Override
	public int getX() {
		// TODO Autogenerated method stub
		return 0;
	}

	@Override
	public int getY() {
		// TODO Autogenerated method stub
		return 0;
	}

	@Override
	public boolean isAlive() {
		// TODO Autogenerated method stub
		return false;
	}

	@Override
	public boolean isHit(int newX, int newY) {
		// TODO Autogenerated method stub
		return false;
	}

	@Override
	public Point getPosition() {
		// TODO Autogenerated method stub
		return null;
	}

	@Override
	public void setOrientation(int orientation) {
		// TODO Autogenerated method stub

	}

	@Override
	public int getOrientation() {
		// TODO Autogenerated method stub
		return 0;
	}

	@Override
	public boolean isOnWall(int newX, int newY) {
		// TODO Autogenerated method stub
		return false;
	}

	@Override
	public void die() {
		// TODO Autogenerated method stub

	}

}